on: workflow_dispatch

jobs:
  generate-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          intall-r: 'false'

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true  
          
      - name: prepare a new branch
        run: |
          git branch refresh_data
          git checkout refresh_data
          git rm ./data/*.Rds

      - name: Download and process data
        run: |
          Rscript R/download_income_mobility.R

      - name: Commit files
        run: |
          git add ./data
          git commit -S -m "updated income and mobility data (through GitHub Actions)"
          git push --upstream origin refresh_data

